// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCK2Zfn8A9dZyE8xhdDc0VljNpXZEzJy0',
    appId: '1:825328970026:android:882059b8d990c02ff79653',
    messagingSenderId: '825328970026',
    projectId: 'furniture-41729',
    storageBucket: 'furniture-41729.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmXcqjc1XWgBSl9phzFwiP90RVvHDnwVs',
    appId: '1:825328970026:ios:7f3ecb235c7da5bdf79653',
    messagingSenderId: '825328970026',
    projectId: 'furniture-41729',
    storageBucket: 'furniture-41729.appspot.com',
    iosBundleId: 'com.example.furniture',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTfFZxR5b8wUAr1jipV7DpcwSpQhAyJmI',
    appId: '1:825328970026:web:c00c25481c4df7ccf79653',
    messagingSenderId: '825328970026',
    projectId: 'furniture-41729',
    authDomain: 'furniture-41729.firebaseapp.com',
    storageBucket: 'furniture-41729.appspot.com',
    measurementId: 'G-HE8JL3VGRV',
  );

}